name: CI

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: privapps/git-fetch-merge@dev-action
        with:
          target-url: 'https://raw.githubusercontent.com/privapps/git-fetch-merge/data-4-test/data.tar.xz'
          extracted-folder: 'data'
          no-trace: false
